### ISSUE TITLE
CCTV fails if there are changes in the layer text.

### ISSUE THREAD

**Issue by 10zinten** [OpenPoti/openpoti-toolkit#8]
## CCTV fails at following cases:

srcbl = `abefghijkl`
dstbl = `abcdefgkl`
CCTV = `[(0, 2, 0), (2, 5, 2), (8, 10, -1)]`

Note: `-` is the annotation

Cases:
1. Changes at beginning of layer text

    |          |source      |destination|
    |----------|------------|-----------|
    |layer_text|ab-efg-hijkl|abc-defg-kl|
    |anno      |(2,4)       |(3,6)      |

    get_updated_coord():
         - input = 2, cctv = 2, output = 2+2 = 4
         - input = 4, cctv = 2, output = 4+2 = 6

    Expected output should be `(3, 6)`

2. Changes at end of layer text
   
    |          |source      |destination|
    |----------|------------|-----------|
    |layer_text|ab-efghijk-l|abcd-efg-kl|
    |anno      |(2,8)       |(4,6)      |

    get_updated_coord():
         - input = 2, cctv = 2, output = 2+2 = 4
         - input = 8, cctv = -1, output = 8-1 = 6

    Expected output should be `(3, 6)`

**Comment by 10zinten** [comment]
is getting corresponding start and end of source annotation a way to get updated annotation, like I did in the example above ?

**Comment by eroux** [comment]
I'm struggling a bit with your case here... let's take the first one. What I understand is:

you have an initial base layer + annotation of `ab-efg-hijkl`, and you update the base layerto be `abcdefgkl`. Then you want the initial annotation to be `abc-defg-kl`?

If so, that's just impossible, there's not enough information anywhere to know that the annotation should be `abc-defg-kl` instead of `ab-cdefg-kl` or `abcd-efg-kl`. In this case the method with the cctv should actually return `-1` because it can't know for sure. Then the method with `dmp` should be applied, and chances are that it will find that `ab-cdefg-kl` is the best option.

Does it answer your question?

**Comment by 10zinten** [comment]
Okay I understand the point of dmp.

But is the correct way that we take only start and end of annotation from source, eg (2, 4) and get the updated annotation ?

**Comment by eroux** [comment]
I think the problem here is a side effect: I probably initially took an optimistic approach but your example shows that when a coordinate is on a side of a rage in the cctv, we shouldn't decide where it should go. So when the cctv has `[(0, 2, 0), (2, 5, 2), (8, 10, -1)]` and we're looking for the new coordinate of position `2` (or `5` or `8` or `10)`, we should return `-1` and let dmp find the best spot

**Comment by 10zinten** [comment]
Okay so, is it fine that we got `ab-cdefg-kl` instead of `ab-defg-kl` ?

**Comment by eroux** [comment]
you mean that `ab-cdefg-kl` gets updated into `ab-defg-kl`? in the end yes, but I think we should involve dmp when looking for the update of the first coordinate

**Comment by 10zinten** [comment]
Okay got it, thanks
